name: Daily Tweet Bot

on:
  schedule:
    - cron: "15 10 * * *"  # Runs every day at 10:30 UTC (13:30 Türkiye time)
  workflow_dispatch:      # Also allow manual runs from GitHub UI

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tweet script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: |
          python post_tweet.py
